name: Demo

on: 
  schedule:
    - cron: '*/5 1-23/2 23 * *'

jobs:
  init:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: Echo "HelloWorld!!First script is sucess!!!!!!"
