name: Demo

on: push
  # schedule:
  #  - cron: '*/5 * * * *'

jobs:
  init:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: Echo "HelloWorld!!First script is sucess!!!!!!"
