name: Demo

on: 
  # workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  init:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: Echo "HelloWorld!!First script is sucess!!!!!!:-)"
