name: Demo

on: 
  schedule:
  - cron: '51 16 23 5 1'

jobs:
  init:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: Echo "HelloWorld!!First script is sucess!!!!!!"
