name: SchedulerDemo

on: 
  schedule:
    - cron: "45 5,17 * * *"

jobs:
  SD-myJob:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: Echo "Scheduler demo is success"
